## Creating, Reading and Writing

Ejercicio 1. Create a DataFrame "fruits".

In [53]:
import pandas as pd

# Your code goes here. Create a dataframe matching the above diagram and assign it to the variable fruits. 
fruits = pd.DataFrame({'Apples': [30], 'Bananas':[21]})

Ejercicio 2. Create a dataframe "fruit_sales" that matches.

In [54]:
fruit_sales = pd.DataFrame({'Apples': [35, 41], 'Bananas':[21, 34]}, index = ['2017 Sales', '2018 Sales'])
fruit_sales

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

Ejercicio 3. Create a variable "ingredients" with a Series.

In [55]:
ingredients = pd.Series(['4 cups','1 cup','2 large','1 can'], index=['Flour','Milk','Eggs','Spam'],name="Dinner")
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

Ejercicio 4. Read the following csv dataset of wine reviews called "reviews.

In [56]:
reviews = pd.read_csv('C:/Users/jorge/OneDrive - Universidad Alfonso X el Sabio/Escritorio/kaggle/Pandas/winemag-data_first150k.csv',index_col=0)
reviews

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
...,...,...,...,...,...,...,...,...,...,...
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

Ejercicio 5. Run the cell beow to create and display a DataFrame called "animals"

In [57]:
animals = pd.DataFrame({'cows':[12, 20], 'Goats':[22, 19]}, index=['Year 1','Year 2'])
animals

        cows  Goats
Year 1    12     22
Year 2    20     19

## Indexing, Selecting & Assigning

Ejercicio 1. Select the description column from reviews and assign the result to the variable desc.

In [58]:
desc = reviews.description

Ejercicio 2. Select the first value from the description column of reviews, assigning it to variable first_description.

In [59]:
first_description = reviews.description[0]
first_description

'This tremendous 100% varietal wine hails from Oakville and was aged over three years in oak. Juicy red-cherry fruit and a compelling hint of caramel greet the palate, framed by elegant, fine tannins and a subtle minty tone in the background. Balanced and rewarding from start to finish, it has years ahead of it to develop further nuance. Enjoy 2022–2030.'

Ejercicio 3. Select the first row of data (the first record)from reviews, assigning it to the variable first_row.

In [60]:
first_row = reviews.iloc[0,:]
first_row

country                                                       US
description    This tremendous 100% varietal wine hails from ...
designation                                    Martha's Vineyard
points                                                        96
price                                                      235.0
province                                              California
region_1                                             Napa Valley
region_2                                                    Napa
variety                                       Cabernet Sauvignon
winery                                                     Heitz
Name: 0, dtype: object

Ejercicio 4. Select the first 10 values from the description column in reviews, assigning the result to variable first_descriptions.

In [61]:
first_descriptions = reviews.description.head(10)
first_descriptions

0    This tremendous 100% varietal wine hails from ...
1    Ripe aromas of fig, blackberry and cassis are ...
2    Mac Watson honors the memory of a wine once ma...
3    This spent 20 months in 30% new French oak, an...
4    This is the top wine from La Bégude, named aft...
5    Deep, dense and pure from the opening bell, th...
6    Slightly gritty black-fruit aromas include a s...
7    Lush cedary black-fruit aromas are luxe and of...
8    This re-named vineyard was formerly bottled as...
9    The producer sources from two blocks of the vi...
Name: description, dtype: object

Ejercicio 5. Select the records with index labels 1, 2, 3, 5, and 8, assigning the result to the variable sample_reviews.

In [62]:
indices = [1,2,3,5,8]
sample_reviews = reviews.loc[indices]
sample_reviews

,country,description,designation,points,price,province,region_1,region_2,variety,winery
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
5,Spain,"Deep, dense and pure from the opening bell, th...",Numanthia,95,73.0,Northern Spain,Toro,NaN,Tinta de Toro,Numanthia
8,US,This re-named vineyard was formerly bottled as...,Silice,95,65.0,Oregon,Chehalem Mountains,Willamette Valley,Pinot Noir,Bergström

Ejercicio 6. Create a variable df containing the country, province, region_1, and region_2 columns of the records with the index labels 0,1,10, and 100. In other words, generate the following DataFrame.

In [63]:
cols = ['country','province','region_1','region_2']
indices = [0,1,10,100]
df = reviews.loc[indices,cols]
df

    country            province     region_1     region_2
0        US          California  Napa Valley         Napa
1     Spain      Northern Spain         Toro          NaN
10    Italy  Northeastern Italy       Collio          NaN
100      US          California  South Coast  South Coast

Ejercicio 7. Create a variable df containing the country and variety columns of the first 100 records.

In [64]:
cols = ['country','variety']
df = reviews.loc[:99,cols]
df

   country               variety
0       US    Cabernet Sauvignon
1    Spain         Tinta de Toro
2       US       Sauvignon Blanc
3       US            Pinot Noir
4   France    Provence red blend
..     ...                   ...
95  France         Malbec-Merlot
96      US            Chardonnay
97      US    Cabernet Sauvignon
98  France         Merlot-Malbec
99  France  Ugni Blanc-Colombard

[100 rows x 2 columns]

Ejercicio 8. Create a DataFrame italian_wines containing reviews of wines made in Italy.

In [65]:
italian_wines = reviews[reviews.country == 'Italy']
italian_wines

,country,description,designation,points,price,province,region_1,region_2,variety,winery
10,Italy,"Elegance, complexity and structure come togeth...",Ronco della Chiesa,95,80.0,Northeastern Italy,Collio,NaN,Friulano,Borgo del Tiglio
32,Italy,"Underbrush, scorched earth, menthol and plum s...",Vigna Piaggia,90,NaN,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Abbadia Ardenga
35,Italy,"Forest floor, tilled soil, mature berry and a ...",Riserva,90,135.0,Tuscany,Brunello di Montalcino,NaN,Sangiovese,Carillon
37,Italy,"Aromas of forest floor, violet, red berry and ...",NaN,90,29.0,Tuscany,Vino Nobile di Montepulciano,NaN,Sangiovese,Avignonesi
38,Italy,"This has a charming nose that boasts rose, vio...",NaN,90,23.0,Tuscany,Chianti Classico,NaN,Sangiovese,Casina di Cornia
...,...,...,...,...,...,...,...,...,...,...
150920,Italy,"Rich and mature aromas of smoke, earth and her...",Brut Riserva,91,19.0,Northeastern Italy,Trento,NaN,Champagne Blend,Letrari
150922,Italy,Made by 30-ish Roberta Borghese high above Man...,Superiore,91,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,Tocai,Ronchi di Manzano
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

Ejercicio 9. Create a DataFrame top_oceania_wines containing all reviews with at least 95 points (out of 100) for wines from Australia or New Zealand.

In [66]:
top_oceania_wines = reviews.loc[(reviews.country.isin(['Australia','New Zealand'])) & (reviews.points >= 95)]
top_oceania_wines

,country,description,designation,points,price,province,region_1,region_2,variety,winery
2148,Australia,Full-bodied and plush yet vibrant and imbued w...,The Factor,98,125.0,South Australia,Barossa Valley,NaN,Shiraz,Torbreck
2458,Australia,This is a top example of the classic Australia...,The Peake,96,150.0,South Australia,McLaren Vale,NaN,Cabernet-Shiraz,Hickinbotham
3033,Australia,This Cabernet equivalent to Grange has explode...,Bin 707,95,500.0,South Australia,South Australia,NaN,Cabernet Sauvignon,Penfolds
3044,Australia,"From vines planted in 1912, this has been an i...",Mount Edelstone Vineyard,95,200.0,South Australia,Eden Valley,NaN,Shiraz,Henschke
3047,Australia,"This is a throwback to those brash, flavor-exu...",One,95,95.0,South Australia,Langhorne Creek,NaN,Red Blend,Heartland
...,...,...,...,...,...,...,...,...,...,...
122779,Australia,If Standish's Relic is the feminine side of Sh...,The Standish Single Vineyard,96,135.0,South Australia,Barossa Valley,NaN,Shiraz,Standish
127614,Australia,This stellar wine takes a little time in the g...,Hill of Grace,95,625.0,South Australia,Eden Valley,NaN,Shiraz,Henschke
137383,Australia,The 2007 Astralis impresses for its combinatio...,Astralis,95,225.0,South Australia,Clarendon,NaN,Syrah,Clarendon Hills
150562,Australia,"As unevolved as they are, the dense and multil...",Grange,96,185.0,South Australia,South Australia,NaN,Shiraz,Penfolds
150563,Australia,"Seamless luxury from stem to stern, this ‘baby...",RWT,95,70.0,South Australia,Barossa Valley,NaN,Shiraz,Penfolds

## Summary Functions and Maps

Ejercicio 1. What is the median of the points column in the reviews DataFrame?

In [67]:
median_points = reviews.points.median()
median_points

88.0

Ejercicio 2. What countries are represented in the dataset? (Your answer should not include any duplicates)

In [68]:
reviews.country.unique()

array(['US', 'Spain', 'France', 'Italy', 'New Zealand', 'Bulgaria',
       'Argentina', 'Australia', 'Portugal', 'Israel', 'South Africa',
       'Greece', 'Chile', 'Morocco', 'Romania', 'Germany', 'Canada',
       'Moldova', 'Hungary', 'Austria', 'Croatia', 'Slovenia', nan,
       'India', 'Turkey', 'Macedonia', 'Lebanon', 'Serbia', 'Uruguay',
       'Switzerland', 'Albania', 'Bosnia and Herzegovina', 'Brazil',
       'Cyprus', 'Lithuania', 'Japan', 'China', 'South Korea', 'Ukraine',
       'England', 'Mexico', 'Georgia', 'Montenegro', 'Luxembourg',
       'Slovakia', 'Czech Republic', 'Egypt', 'Tunisia', 'US-France'],
      dtype=object)

Ejercicio 3. How often does each country appear in the dataset? Create a Series reviews_per_country mapping countries to the count of reviews of wines from that country.

In [69]:
reviews_per_country = reviews.country.value_counts()
reviews_per_country

country
US                        62397
Italy                     23478
France                    21098
Spain                      8268
Chile                      5816
Argentina                  5631
Portugal                   5322
Australia                  4957
New Zealand                3320
Austria                    3057
Germany                    2452
South Africa               2258
Greece                      884
Israel                      630
Hungary                     231
Canada                      196
Romania                     139
Slovenia                     94
Uruguay                      92
Croatia                      89
Bulgaria                     77
Moldova                      71
Mexico                       63
Turkey                       52
Georgia                      43
Lebanon                      37
Cyprus                       31
Brazil                       25
Macedonia                    16
Serbia                       14
Morocco                      12
England                       9
Luxembourg                    9
Lithuania                     8
India                         8
Czech Republic                6
Ukraine                       5
Switzerland                   4
South Korea                   4
Bosnia and Herzegovina        4
China                         3
Egypt                         3
Slovakia                      3
Tunisia                       2
Albania                       2
Montenegro                    2
Japan                         2
US-France                     1
Name: count, dtype: int64

Ejercicio 4. Create variable centered_price containing a version of the price column with the mean price subtracted.

In [70]:
centered_price = reviews.price - reviews.price.mean()
centered_price

0         201.868518
1          76.868518
2          56.868518
3          31.868518
4          32.868518
             ...
150925    -13.131482
150926     -6.131482
150927    -13.131482
150928     18.868518
150929    -18.131482
Name: price, Length: 150930, dtype: float64

Ejercicio 5. I'm an economical wine buyer. Wich wine is the "best bargain"? Create a variable bargain_wine with the title of the wine with the highest points-to-price ratio in the dataset.

In [71]:
bargain_idx = (reviews.points / reviews.price).idxmax()
bargain_wine = reviews.loc[bargain_idx, reviews.columns.str.strip() == 'title']

Ejercicio 6. Create a Series descriptor_counts counting how many times each of these two words appears in the description column in the dataset.

In [72]:
n_trop = reviews.description.map(lambda desc: "tropical" in desc).sum()
n_fruity = reviews.description.map(lambda desc: "fruity" in desc).sum()
descriptor_counts = pd.Series([n_trop, n_fruity], index=['tropical','fruity'])
descriptor_counts

tropical    4135
fruity      8669
dtype: int64

Ejercicio 7. We'd like to host thse wine reviews on our website, but a rating system ranging from 80 to 100 points is too hard to understand - we'd like to translate them into simple ratings. A score of 95 or higher counts as 3 stars, a score of at least 85 but less than 95 is 2 stars. Any other score is 1 star.
Create a series star_ratings with the number of stars corresponding to each review in the dataset.

In [73]:
def stars(row):
    if row.country == 'Canada':
        return 3
    elif row.points >= 95:
        return 3
    elif row.points >= 85:
        return 2
    else:
        return 1
    
    star_ratings = reviews.apply(stars, axis='columns')

## Grouping and Sorting

Ejercicio 1. Create a Series whose index is the taster_twitter_handle category from the dataset, and whose values count how many reviews each person wrote.

In [74]:
# cargar el dataset
reviews1 = pd.read_csv('C:/Users/jorge/OneDrive - Universidad Alfonso X el Sabio/Escritorio/kaggle/Pandas/winemag-data-130k-v2.csv',index_col=0)
reviews1

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [75]:
# opción 1
reviews_written = reviews1.groupby('taster_twitter_handle').size()

In [76]:
# opción 2
reviews_written = reviews1.groupby('taster_twitter_handle').taster_twitter_handle.count()

Ejercicio 2. What is the best wine I can buy for a given amount of money? Create a Series whose index is wine prices and whose values is the maximum number of points a wine costing that much was given in a review. Sort the values by price, ascending ( so that 4.0 dollars is at the top and 3300.0 dollars is at the bottom).

In [77]:
best_rating_per_price = reviews1.groupby('price')['points'].max().sort_index()
best_rating_per_price

price
4.0       86
5.0       87
6.0       88
7.0       91
8.0       91
          ..
1900.0    98
2000.0    97
2013.0    91
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

Ejercicio 3. What are the minimum and maximum prices for each variety of wine? Create a DataFrame whose index is the variety category from the dataset and whose values are the min and max values thereof.

In [78]:
price_extremes = reviews1.groupby('variety').price.agg([min,max])
price_extremes

C:\Users\jorge\AppData\Local\Temp\ipykernel_6508\1083874347.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  price_extremes = reviews1.groupby('variety').price.agg([min,max])
C:\Users\jorge\AppData\Local\Temp\ipykernel_6508\1083874347.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  price_extremes = reviews1.groupby('variety').price.agg([min,max])

              min    max
variety
Abouriou     15.0   75.0
Agiorgitiko  10.0   66.0
Aglianico     6.0  180.0
Aidani       27.0   27.0
Airen         8.0   10.0
...           ...    ...
Zinfandel     5.0  100.0
Zlahtina     13.0   16.0
Zweigelt      9.0   70.0
Çalkarası    19.0   19.0
Žilavka      15.0   15.0

[707 rows x 2 columns]

Ejercicio 4. What are the most expensive wine varieties? Create a variable sorted_varieties containing a copy of the dataframe from the previous question where varieties are sorted in descending order based on minimum price, the on maximum price (to break tries)

In [79]:
sorted_varieties = price_extremes.sort_values(by=['min', 'max'], ascending=False)
sorted_varieties

                                  min    max
variety
Ramisco                         495.0  495.0
Terrantez                       236.0  236.0
Francisa                        160.0  160.0
Rosenmuskateller                150.0  150.0
Tinta Negra Mole                112.0  112.0
...                               ...    ...
Roscetto                          NaN    NaN
Sauvignon Blanc-Sauvignon Gris    NaN    NaN
Tempranillo-Malbec                NaN    NaN
Vital                             NaN    NaN
Zelen                             NaN    NaN

[707 rows x 2 columns]

Ejercicio 5. Create a Series whose index is reviewers and whose values is the average review score given out by that reviewer. Hint: you will need the taster_name and points columns.

In [80]:
reviewer_mean_ratings = reviews1.groupby('taster_name').points.mean()
reviewer_mean_ratings

taster_name
Alexander Peartree    85.855422
Anna Lee C. Iijima    88.415629
Anne Krebiehl MW      90.562551
Carrie Dykes          86.395683
Christina Pickard     87.833333
Fiona Adams           86.888889
Jeff Jenssen          88.319756
Jim Gordon            88.626287
Joe Czerwinski        88.536235
Kerin O’Keefe         88.867947
Lauren Buzzeo         87.739510
Matt Kettmann         90.008686
Michael Schachner     86.907493
Mike DeSimone         89.101167
Paul Gregutt          89.082564
Roger Voss            88.708003
Sean P. Sullivan      88.755739
Susan Kostrzewa       86.609217
Virginie Boone        89.213379
Name: points, dtype: float64

Are there significant differences in the average scores assigned by the various reviewers? Run the cell bellow to use the describe() method to see a summary of the range of values.

In [81]:
reviewer_mean_ratings.describe()

count    19.000000
mean     88.233026
std       1.243610
min      85.855422
25%      87.323501
50%      88.536235
75%      88.975256
max      90.562551
Name: points, dtype: float64

Ejercicio 6. What combination of countries and varieties are most common? Create a Series whose index is a MultiIndex of {country, variety} pairs. For example, a pinot noir produced in the US should map to {"US", "Pinot Noir"}. Sort the values in the Series in descending order based on wine count.

In [82]:
country_variety_counts = reviews1.groupby(['country', 'variety']).size().sort_values(ascending=False)
country_variety_counts

country  variety
US       Pinot Noir                  9885
         Cabernet Sauvignon          7315
         Chardonnay                  6801
France   Bordeaux-style Red Blend    4725
Italy    Red Blend                   3624
                                     ...
Mexico   Cinsault                       1
         Grenache                       1
         Merlot                         1
         Rosado                         1
Uruguay  White Blend                    1
Length: 1612, dtype: int64

## Data Types and Missing Values

Ejercicio 1. What is the data type of the points column in the dataset?

In [83]:
dtype = reviews1.points.dtypes
dtype

dtype('int64')

Ejercicio 2. Create a Series from entries in the points column, but convert the entries to strins. Hint: strings are str in native Python.

In [84]:
point_strings = reviews1.points.astype('str')
point_strings

0         87
1         87
2         87
3         87
4         87
          ..
129966    90
129967    90
129968    90
129969    90
129970    90
Name: points, Length: 129971, dtype: object

Ejercicio 3. Sometimes the price column is null. How many reviews in the dataset are missing a price?

In [85]:
n_missing_prices = pd.isnull(reviews1.price).sum()
n_missing_prices

8996

Ejercicio 4. What are the most common wine-producing regions? Create a Series counting the number of times each value occurs in the region_1 field. This field is often missing data, so replace missing values with Unknown. Sort in descending order.

In [86]:
reviews_per_region = reviews1.region_1.fillna('Unknown').value_counts().sort_values(ascending=False)
reviews_per_region

region_1
Unknown                 21247
Napa Valley              4480
Columbia Valley (WA)     4124
Russian River Valley     3091
California               2629
                        ...
Offida Rosso                1
Corton Perrières            1
Isle St. George             1
Geelong                     1
Paestum                     1
Name: count, Length: 1230, dtype: int64

## Renaming and Combining

In [87]:
reviews1.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

Ejemplo 1. region_1 and region_2 are pretty uninformative names for locale columns in the dataset. Create a copy of reviews with these columns renamed to region and locale, respectively.

In [88]:
renamed = reviews1.rename(columns={'region_1':'region','region_2':'locale'})
renamed

,country,description,designation,points,price,province,region,locale,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

Ejercicio 2. Set the index name in the dataset to wines.

In [89]:
reindexed = reviews1.rename_axis('wines', axis='rows')
reindexed

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
wines,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

Ejercicio 3. The Things on Reddit dataset includes product links from a selection of top-ranked forums("subreddits")on reddit.com. Run the cell below to load a dataframe of products mentioned on  the /r/gaming subreddit and another dataframe for products mentioned on the r//movies subreddit.

In [90]:
gaming_products = pd.read_csv('C:/Users/jorge/OneDrive - Universidad Alfonso X el Sabio/Escritorio/kaggle/Pandas/games.csv',index_col=0)
gaming_products['subreddit'] = "r/gaming"
movie_products = pd.read_csv('C:/Users/jorge/OneDrive - Universidad Alfonso X el Sabio/Escritorio/kaggle/Pandas/movies.csv',index_col=0)
movie_products['subreddit'] = "r/movies"

Create a DataFrame of products mentioned on either subreddit.

In [91]:
combined_products = pd.concat([gaming_products, movie_products])
combined_products

,rated,created_at,last_move_at,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply,subreddit,category,amazon_link,total_mentions,subreddit_mentions
TZJHLljE,False,1.504210e+12,1.504210e+12,13.0,outoftime,white,15+2,bourgris,1500.0,a-00,1191.0,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,Slav Defense: Exchange Variation,5.0,r/gaming,NaN,NaN,NaN,NaN
l1NXvwaE,True,1.504130e+12,1.504130e+12,16.0,resign,black,5+10,a-00,1322.0,skinnerua,1261.0,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,Nimzowitsch Defense: Kennedy Variation,4.0,r/gaming,NaN,NaN,NaN,NaN
mIICvQHh,True,1.504130e+12,1.504130e+12,61.0,mate,white,5+10,ischia,1496.0,a-00,1500.0,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,King's Pawn Game: Leonardis Variation,3.0,r/gaming,NaN,NaN,NaN,NaN
kWKvrqYL,True,1.504110e+12,1.504110e+12,61.0,mate,white,20+0,daniamurashov,1439.0,adivanov2009,1454.0,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,Queen's Pawn Game: Zukertort Variation,3.0,r/gaming,NaN,NaN,NaN,NaN
9tXo1AUZ,True,1.504030e+12,1.504030e+12,95.0,mate,white,30+3,nik221107,1523.0,adivanov2009,1469.0,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,Philidor Defense,5.0,r/gaming,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Magic Makers - One Way Joker Forcing Red Back Deck In Bicycle Stock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,r/movies,Toys & Games,https://www.amazon.com/Magic-Makers-Joker-Forc...,1.0,1.0
SDCC 2015 SPACEBALLS Dark Helmet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,r/movies,Toys & Games,https://www.amazon.com/SDCC-2015-SPACEBALLS-Da...,1.0,1.0
The Sounds of Star Wars,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,r/movies,Books,https://www.amazon.com/Sounds-Star-Wars-J-Rinz...,1.0,1.0
Come with Me [CD-Single],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,r/movies,CDs & Vinyl,https://www.amazon.com/dp/B000007QDG/ref=cm_sw...,1.0,1.0
I Am Legend,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,r/movies,Movies & TV,https://www.amazon.com/Am-Legend-Blu-ray-Will-...,1.0,1.0

Ejercicio 4. The Powerlifting Database dataset on Kaggle includes one CSV table for powerlifting meets and a separate one for powerlifting competitors. Run the cell below to load these datasets into dataframes:

In [94]:
powerlifting_meets = pd.read_csv('C:/Users/jorge/OneDrive - Universidad Alfonso X el Sabio/Escritorio/kaggle/Pandas/meets.csv',index_col=0)
powerlifting_competitors = pd.read_csv('C:/Users/jorge/OneDrive - Universidad Alfonso X el Sabio/Escritorio/kaggle/Pandas/openpowerlifting.csv',index_col=0)
powerlifting_competitors

,Name,Sex,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
MeetID,,,,,,,,,,,,,,,,
0,Angie Belk Terry,F,Wraps,47.0,Mst 45-49,59.60,60,NaN,47.63,NaN,20.41,NaN,70.31,138.35,1,155.05
0,Dawn Bogart,F,Single-ply,42.0,Mst 40-44,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
0,Dawn Bogart,F,Single-ply,42.0,Open Senior,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
0,Dawn Bogart,F,Raw,42.0,Open Senior,58.51,60,NaN,NaN,NaN,95.25,NaN,NaN,95.25,1,108.29
0,Destiny Dula,F,Raw,18.0,Teen 18-19,63.68,67.5,NaN,NaN,NaN,31.75,NaN,90.72,122.47,1,130.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8481,William Barabas,M,Multi-ply,NaN,Elite,113.58,125,NaN,NaN,NaN,NaN,NaN,347.50,347.50,2,202.60
8481,Justin Zottl,M,Multi-ply,NaN,Elite,119.02,125,NaN,NaN,NaN,NaN,NaN,322.50,322.50,3,185.77
8481,Jake Anderson,M,Multi-ply,NaN,Elite,120.29,125,NaN,NaN,NaN,NaN,NaN,367.50,367.50,1,211.17
8481,Jeff Bumanglag,M,Multi-ply,NaN,Elite,126.73,140,NaN,NaN,NaN,NaN,NaN,320.00,320.00,3,181.85
8481,Shane Hammock,M,Multi-ply,NaN,Elite,129.46,140,NaN,NaN,NaN,NaN,NaN,362.50,362.50,2,205.18

Both tables include references to a MeetID, a unique key for each meet (competition)included in the database. Using this, generate a dataset combining the two tables into one.

In [95]:
powerlifting_combined = pd.merge(powerlifting_competitors, powerlifting_meets, on="MeetID", how="inner")
powerlifting_combined

,Name,Sex,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,...,TotalKg,Place,Wilks,MeetPath,Federation,Date,MeetCountry,MeetState,MeetTown,MeetName
MeetID,,,,,,,,,,,,,,,,,,,,,
0,Angie Belk Terry,F,Wraps,47.0,Mst 45-49,59.60,60,NaN,47.63,NaN,...,138.35,1,155.05,365strong/1601,365Strong,2016-10-29,USA,NC,Charlotte,2016 Junior & Senior National Powerlifting Cha...
0,Dawn Bogart,F,Single-ply,42.0,Mst 40-44,58.51,60,NaN,142.88,NaN,...,401.42,1,456.38,365strong/1601,365Strong,2016-10-29,USA,NC,Charlotte,2016 Junior & Senior National Powerlifting Cha...
0,Dawn Bogart,F,Single-ply,42.0,Open Senior,58.51,60,NaN,142.88,NaN,...,401.42,1,456.38,365strong/1601,365Strong,2016-10-29,USA,NC,Charlotte,2016 Junior & Senior National Powerlifting Cha...
0,Dawn Bogart,F,Raw,42.0,Open Senior,58.51,60,NaN,NaN,NaN,...,95.25,1,108.29,365strong/1601,365Strong,2016-10-29,USA,NC,Charlotte,2016 Junior & Senior National Powerlifting Cha...
0,Destiny Dula,F,Raw,18.0,Teen 18-19,63.68,67.5,NaN,NaN,NaN,...,122.47,1,130.47,365strong/1601,365Strong,2016-10-29,USA,NC,Charlotte,2016 Junior & Senior National Powerlifting Cha...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8481,William Barabas,M,Multi-ply,NaN,Elite,113.58,125,NaN,NaN,NaN,...,347.50,2,202.60,xpc/2017-finals,XPC,2017-03-03,USA,OH,Columbus,2017 XPC Finals
8481,Justin Zottl,M,Multi-ply,NaN,Elite,119.02,125,NaN,NaN,NaN,...,322.50,3,185.77,xpc/2017-finals,XPC,2017-03-03,USA,OH,Columbus,2017 XPC Finals
8481,Jake Anderson,M,Multi-ply,NaN,Elite,120.29,125,NaN,NaN,NaN,...,367.50,1,211.17,xpc/2017-finals,XPC,2017-03-03,USA,OH,Columbus,2017 XPC Finals
8481,Jeff Bumanglag,M,Multi-ply,NaN,Elite,126.73,140,NaN,NaN,NaN,...,320.00,3,181.85,xpc/2017-finals,XPC,2017-03-03,USA,OH,Columbus,2017 XPC Finals
8481,Shane Hammock,M,Multi-ply,NaN,Elite,129.46,140,NaN,NaN,NaN,...,362.50,2,205.18,xpc/2017-finals,XPC,2017-03-03,USA,OH,Columbus,2017 XPC Finals